CREATE DATABASE IF NOT EXISTS Tourism;
USE Tourism;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('Admin', 'User', 'Guide', 'Tourist') NOT NULL DEFAULT 'Tourist',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
